# Generated by Django 5.2.5 on 2025-08-28 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bookingId', models.AutoField(primary_key=True, serialize=False)),
                ('numberOfSeatsBooked', models.IntegerField(default=1)),
                ('totalPrice', models.FloatField()),
                ('bookingDate', models.DateField()),
                ('status', models.CharField(choices=[('CONFIRMED', '✅ CONFIRMED'), ('CANCELLED', '❌ CANCELLED')], default='CANCELLED', max_length=10)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.travel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
