# Generated by Django 5.2.5 on 2025-08-28 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('placeName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('travelId', models.AutoField(primary_key=True, serialize=False)),
                ('travelType', models.CharField(choices=[('FLIGHT', 'FLIGHT'), ('TRAIN', 'TRAIN'), ('BUS', 'BUS')], max_length=10)),
                ('bookingDateAndTime', models.DateTimeField()),
                ('price', models.FloatField()),
                ('availableSeats', models.IntegerField()),
                ('discount', models.FloatField(null=True)),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_city', to='travel.places')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_city', to='travel.places')),
            ],
        ),
    ]
